<link rel="stylesheet" href="css/shapes.css" media="all">
<?php 
//include("../lab/header.html");

$strategyHouse = '<table class="">';
$strategyHouse .= '<tr>'
    .'<td class="text-center" colspan="4">'
    .'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="bi bi-flag fs-1"></i>'
    .'</td>'
.'</tr>'
.'<tr>'
    .'<td class="" colspan="4">'
    .'<div class="triangle-up text-left"><p>Vision: A reliable, effective, deposit insurer and resolution authority<br>Mission: To protect depositers and enhance public confidence in the financial system by promoting sound risk management and timely resolution.</p></div>'
    .'</td>'
.'</tr>'
.'<tr>'
.'<td class="float-start">'
        .'<div class="rectangle text-center"><br><i class="bi bi-umbrella fs-4"></i><br><br>Deposit Insurance</div>'
    .'</td>'
    .'<td class="text-center">'
        .'<div class="rectangle text-center"><br><i class="bi bi-sign-stop"></i><br><br>Risk Minimisation</div>'
    .'</td>'
    .'<td style="" class="text-center">'
        .'<div class="rectangle text-center"><br><i class="bi bi-bank fs-4"></i><br><br>Resolution of Problem Banks</div>'
    .'</td>'
    .'<td class="float-end">'
        .'<div class="rectangle text-center"><br><i class="bi bi-graph-up-arrow"></i><br><br>Insitutional Capacity Development</div>'
    .'</td>'
    .'</tr>'
    .'<tr>'
        .'<td colspan="4">'
            .'<div class="rectangleFlat rounded-3 text-center">Core Values</div>'
        .'</td>'
    .'</tr>'
.'</table>';

$strategyHouseTwo = '<table class="">'
.'<tr><td colspan="9" class="text-center"><h3>KDIC Strategy House</h3></td></tr>'
.'<tr>'
    .'<td rowspan="3" class="text-white">left span</td>'
    .'<td colspan="7" class="houseRoof"></td>'
    .'<td rowspan="3" class="text-white">right span</td>'
.'</tr>'
.'<tr>'
    .'<td class="housePillar">'
        .'<table class="text-center table table-borderless">'
            .'<tr>'
                .'<td class="text-center"><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'</tr>'
            .'<tr>'
                .'<td>Deposit<br>Insurance</td>'
            .'</tr>'
        .'</table>'
    .'</td>'
    .'<td>&nbsp;</td>'
    .'<td class="housePillar">'
        .'<table class="text-center table table-borderless">'
            .'<tr>'
                .'<td class="text-center"><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'</tr>'
            .'<tr>'
                .'<td>Risk<br>Minimisation</td>'
            .'</tr>'
        .'</table>'
    .'</td>'
    .'<td>&nbsp;</td>'
    .'<td class="housePillar">'
        .'<table class="text-center table table-borderless">'
            .'<tr>'
                .'<td class="text-center"><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'</tr>'
            .'<tr>'
                .'<td>Resolution of<br>Problem Banks</td>'
            .'</tr>'
        .'</table>'
    .'</td>'
    .'<td>&nbsp;</td>'
    .'<td class="housePillar">'
        .'<table class="text-center table table-borderless">'
            .'<tr>'
                .'<td class="text-center"><br><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'</tr>'
            .'<tr>'
                .'<td>Insitutional<br>Capacity<br>Development</td>'
            .'</tr>'
        .'</table>'
    .'</td>'
.'</tr>'
.'<tr>'
    .'<td colspan="7" class="houseBeam"></td>'
.'</tr>'
.'<tr>'
    .'<td colspan="9" class="houseFoundation">'
        .'<table class=" text-white m-0 p-0 w-75 float-end">'
        .'<tr>'
            .'<td><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'<td>Professionalism</td>'
            .'<td><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'<td>Teamwork</td>'
            .'<td><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'<td>Customer Focus</td>'
        .'</tr>'
        .'<tr>'
            .'<td><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'<td>Integrity</td>'
            .'<td><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'<td>Innovativeness</td>'
            .'<td><div style="margin:auto" class="rounded-circle bg-secondary trafficLightBootstrap"></div></td>'
            .'<td>Accountability</td>'
        .'</tr>'
        .'</table'
    .'</td>'
.'</tr>'
.'</table>';

echo $strategyHouseTwo;
//echo $strategyHouse;
?>
